'use strict';

const TEAM_IDS = Object.freeze({
  REIMU: 'reimu',
  MARISA: 'marisa'
});

const ACTIVITY_STATUS = Object.freeze({
  SCHEDULED: 'scheduled',
  RUNNING: 'running',
  PAUSED: 'paused',
  ENDED: 'ended'
});

const CODE_TYPES = Object.freeze({
  ORDINARY: 'ordinary',
  SPECIAL: 'special'
});

const CODE_STATUS = Object.freeze({
  UNUSED: 'unused',
  BOUND: 'bound',
  DISABLED: 'disabled'
});

const LEDGER_KINDS = Object.freeze({
  INTERACTION: 'interaction',
  ADMIN: 'admin',
  STAGE: 'stage',
  SYSTEM: 'system'
});

const SESSION_COOKIE = 'ntjy_session';
const ADMIN_COOKIE = 'ntjy_admin';

const ERROR_CODES = Object.freeze({
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',
  INVALID_CODE: 'INVALID_CODE',
  CODE_ALREADY_USED: 'CODE_ALREADY_USED',
  CODE_DISABLED: 'CODE_DISABLED',
  DUPLICATE_DISPLAY_NAME: 'DUPLICATE_DISPLAY_NAME',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TEAM_JOIN_RESTRICTED: 'TEAM_JOIN_RESTRICTED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_BANNED: 'USER_BANNED',
  ACTIVITY_NOT_RUNNING: 'ACTIVITY_NOT_RUNNING',
  REGION_NOT_FOUND: 'REGION_NOT_FOUND',
  REGION_LOCKED: 'REGION_LOCKED',
  REGION_CLOSED: 'REGION_CLOSED',
  REGION_CLEARED: 'REGION_CLEARED',
  INTERACTION_NOT_FOUND: 'INTERACTION_NOT_FOUND',
  INTERACTION_UNAVAILABLE: 'INTERACTION_UNAVAILABLE',
  ENERGY_NOT_ENOUGH: 'ENERGY_NOT_ENOUGH',
  COOLDOWN_ACTIVE: 'COOLDOWN_ACTIVE',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  PRIZE_NOT_FOUND: 'PRIZE_NOT_FOUND',
  PRIZE_LOCKED: 'PRIZE_LOCKED',
  NO_ELIGIBLE_PLAYERS: 'NO_ELIGIBLE_PLAYERS',
  NO_CHANGE: 'NO_CHANGE'
});

module.exports = {
  TEAM_IDS,
  ACTIVITY_STATUS,
  CODE_TYPES,
  CODE_STATUS,
  LEDGER_KINDS,
  SESSION_COOKIE,
  ADMIN_COOKIE,
  ERROR_CODES
};
